"""empty message

Revision ID: 2c07c347c14d
Revises: c0a5ab74abb2
Create Date: 2025-10-01 12:17:01.301200

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2c07c347c14d'
down_revision: Union[str, Sequence[str], None] = 'c0a5ab74abb2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('news', sa.Column('translated_text', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('news', 'translated_text')
    # ### end Alembic commands ###
