"""empty message

Revision ID: c0a5ab74abb2
Revises: 
Create Date: 2025-09-29 20:11:10.068984

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c0a5ab74abb2'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cifar100',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('image', sa.String(), nullable=False),
    sa.Column('label', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cifar100_id'), 'cifar100', ['id'], unique=False)
    op.create_table('fashion',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('image', sa.Text(), nullable=False),
    sa.Column('label', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_fashion_id'), 'fashion', ['id'], unique=False)
    op.create_table('gtzan',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('audio', sa.String(), nullable=False),
    sa.Column('label', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_gtzan_id'), 'gtzan', ['id'], unique=False)
    op.create_table('mnist',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('image', sa.String(), nullable=False),
    sa.Column('label', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_mnist_id'), 'mnist', ['id'], unique=False)
    op.create_table('news',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('text', sa.String(), nullable=False),
    sa.Column('label', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_news_id'), 'news', ['id'], unique=False)
    op.create_table('speech',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('audio', sa.String(), nullable=False),
    sa.Column('label', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_speech_id'), 'speech', ['id'], unique=False)
    op.create_table('urban',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('audio', sa.String(), nullable=False),
    sa.Column('label', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_urban_id'), 'urban', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_urban_id'), table_name='urban')
    op.drop_table('urban')
    op.drop_index(op.f('ix_speech_id'), table_name='speech')
    op.drop_table('speech')
    op.drop_index(op.f('ix_news_id'), table_name='news')
    op.drop_table('news')
    op.drop_index(op.f('ix_mnist_id'), table_name='mnist')
    op.drop_table('mnist')
    op.drop_index(op.f('ix_gtzan_id'), table_name='gtzan')
    op.drop_table('gtzan')
    op.drop_index(op.f('ix_fashion_id'), table_name='fashion')
    op.drop_table('fashion')
    op.drop_index(op.f('ix_cifar100_id'), table_name='cifar100')
    op.drop_table('cifar100')
    # ### end Alembic commands ###
